package gestionhotel;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class VistaReserva extends javax.swing.JFrame {

    vistaPrincipal nvisPrincipal = new vistaPrincipal();
    static ArrayList<Reserva> reservas = new ArrayList<>();
    static ArbolHabitaciones arbol = new ArbolHabitaciones();
    Reserva nuevaReserva = new Reserva();

    int tipoHabitacion = 0; //////////////////////////////////////////////////////////////
    String nombre = "";
    String nDocu = "";
    int edad = 0;
    String telefono = "";
    int tiempoEstadia = 0;
    int numeroPersonas = 0;
    int diaInicial = 0;

    public VistaReserva(ArbolHabitaciones arbol, ArrayList<Reserva> reservas) {
        this.arbol = arbol;
        this.reservas = reservas;
        nvisPrincipal = new vistaPrincipal(arbol, reservas);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitulo = new javax.swing.JLabel();
        Icono = new javax.swing.JLabel();
        LbDatos = new javax.swing.JLabel();
        LbDatos1 = new javax.swing.JLabel();
        LbDatos2 = new javax.swing.JLabel();
        LbDatos3 = new javax.swing.JLabel();
        LbDatos4 = new javax.swing.JLabel();
        LbDatos5 = new javax.swing.JLabel();
        LbDatos6 = new javax.swing.JLabel();
        LbDatos7 = new javax.swing.JLabel();
        TxtNom = new javax.swing.JTextField();
        TxtNumDoc = new javax.swing.JTextField();
        TxtTele = new javax.swing.JTextField();
        FechaCbox = new javax.swing.JComboBox<>();
        TxtEdad = new javax.swing.JTextField();
        EstadiaCbox = new javax.swing.JComboBox<>();
        NumPerCbox = new javax.swing.JComboBox<>();
        BtnSiguiente = new javax.swing.JButton();
        LbDatos8 = new javax.swing.JLabel();
        HabComboBox = new javax.swing.JComboBox<>();
        BtnVol = new javax.swing.JButton();
        BtnInfo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.SystemColor.window);
        setFocusable(false);
        setFocusableWindowState(false);
        setResizable(false);

        lbTitulo.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        lbTitulo.setText("Sistema De Reservas");

        Icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionhotel/imagenes/WhatsApp Image 2024-05-14 at 9.59.07 AM (2).jpeg"))); // NOI18N

        LbDatos.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        LbDatos.setText("Ingrese sus datos:");

        LbDatos1.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        LbDatos1.setText("N° de documento:");

        LbDatos2.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        LbDatos2.setText("Edad");

        LbDatos3.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        LbDatos3.setText("Nombre Completo:");

        LbDatos4.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        LbDatos4.setText("Fecha deseada para la reserva:");

        LbDatos5.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        LbDatos5.setText("Telefono:");

        LbDatos6.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        LbDatos6.setText("Tiempo de estadía:");

        LbDatos7.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        LbDatos7.setText("Número de personas:");

        TxtNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNomActionPerformed(evt);
            }
        });

        TxtNumDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNumDocActionPerformed(evt);
            }
        });

        TxtTele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTeleActionPerformed(evt);
            }
        });

        FechaCbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "22/05/24", "23/05/24", "24/05/24", "25/05/24", "26/05/24", "27/05/24", "28/05/24", "29/05/24", "30/05/24", "31/05/24", "01/06/24", "02/06/24", "03/06/24", "04/06/24", "05/06/24" }));

        TxtEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtEdadActionPerformed(evt);
            }
        });

        EstadiaCbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Noche", "2 Noches", "3 Noches", "4 Noches", "5 Noches", "6 Noches", "7 Noches", "8 Noches", "9 Noches", "10 Noches" }));

        NumPerCbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));

        BtnSiguiente.setBackground(new java.awt.Color(153, 204, 255));
        BtnSiguiente.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        BtnSiguiente.setText("Siguiente");
        BtnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSiguienteActionPerformed(evt);
            }
        });

        LbDatos8.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        LbDatos8.setText("Tipo de habitacion:");

        HabComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Habitación Estandar Waos", "Habitación SuperWaos" }));
        HabComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HabComboBoxActionPerformed(evt);
            }
        });

        BtnVol.setBackground(new java.awt.Color(153, 204, 255));
        BtnVol.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BtnVol.setText(" inicio");
        BtnVol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolActionPerformed(evt);
            }
        });

        BtnInfo.setFont(new java.awt.Font("Segoe Print", 1, 10)); // NOI18N
        BtnInfo.setForeground(new java.awt.Color(0, 102, 102));
        BtnInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionhotel/imagenes/info4.png"))); // NOI18N
        BtnInfo.setText("Habitaciones");
        BtnInfo.setBorder(null);
        BtnInfo.setBorderPainted(false);
        BtnInfo.setContentAreaFilled(false);
        BtnInfo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnInfo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LbDatos8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HabComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnInfo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addComponent(BtnSiguiente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnVol)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LbDatos1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtNumDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LbDatos)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LbDatos2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LbDatos6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EstadiaCbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LbDatos7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NumPerCbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LbDatos3)
                                .addGap(18, 18, 18)
                                .addComponent(TxtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(LbDatos5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TxtTele))
                                    .addComponent(LbDatos4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FechaCbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lbTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Icono)
                .addGap(91, 91, 91))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Icono))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lbTitulo)))
                .addGap(2, 2, 2)
                .addComponent(LbDatos)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbDatos3)
                    .addComponent(TxtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbDatos1)
                    .addComponent(TxtNumDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbDatos2)
                    .addComponent(TxtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbDatos4)
                    .addComponent(FechaCbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbDatos5)
                    .addComponent(TxtTele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EstadiaCbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbDatos6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbDatos7)
                    .addComponent(NumPerCbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LbDatos8)
                            .addComponent(HabComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnSiguiente)
                            .addComponent(BtnVol)))
                    .addComponent(BtnInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNomActionPerformed

    }//GEN-LAST:event_TxtNomActionPerformed

    private void TxtNumDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNumDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNumDocActionPerformed

    private void TxtTeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTeleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTeleActionPerformed

    private void TxtEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtEdadActionPerformed

    private void BtnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSiguienteActionPerformed

        if (TxtNom.getText().equals("") || TxtNumDoc.equals("") || TxtEdad.getText().equals("") || TxtTele.getText().equals("")) {
            JOptionPane.showMessageDialog(null, " Ningun campo puede estar vacio");
        } else {
            nombre = TxtNom.getText();
            nDocu = TxtNumDoc.getText();

            String edadvalidar = TxtEdad.getText();
            telefono = TxtTele.getText();
            tiempoEstadia = (EstadiaCbox.getSelectedIndex()) + 1;
            numeroPersonas = (NumPerCbox.getSelectedIndex()) + 1;
            diaInicial = (FechaCbox.getSelectedIndex()) + 1;
            tipoHabitacion = HabComboBox.getSelectedIndex();
            if (CantCarac(nDocu) == true && esNumero(nDocu) == true) {
                if (esNumero(edadvalidar) == false) {
                    edad = Integer.parseInt(TxtEdad.getText());
                    if (edad >= 18 && edad <= 90) {
                        if (CantCaracTel(telefono) == true && esNumero(telefono) == true) {
                            if (nuevaReserva.ReservarHabitacion(diaInicial, tiempoEstadia)) {
                                if (tipoHabitacion == 0) {
                                    int index = arbol.dispHabitacionesNormales();
                                    if (index >= 0) {
                                        nuevaReserva = new Reserva(nombre, nDocu, edad, telefono, tiempoEstadia, numeroPersonas, index + 1);
                                        reservas.add(nuevaReserva);
                                        arbol.habitacionesNormalesEnc(index);
                                        arbol.printInOrder();
                                        JOptionPane.showMessageDialog(null, nuevaReserva);
                                    } else {
                                        JOptionPane.showMessageDialog(null, "No hay habitaciones normales disponibles");
                                    }
                                     if (numeroPersonas >= 0) {
                                        vistaPrincipal nvisPrincipal=new vistaPrincipal(arbol, reservas);
                                        nvisPrincipal.setVisible(true);
                                        this.dispose();
                                    }
                                } else if (tipoHabitacion == 1) {
                                    int index = arbol.dispHabitacionesEspeciales();
                                    if (index >= 0) {
                                        nuevaReserva = new Reserva(nombre, nDocu, edad, telefono, tiempoEstadia, numeroPersonas, index + 1);
                                        reservas.add(nuevaReserva);
                                        arbol.habitacionesEspecialesEnc(index);
                                        arbol.printInOrder();
                                        JOptionPane.showMessageDialog(null, nuevaReserva);
                                    } else {
                                        JOptionPane.showMessageDialog(null, "No hay habitaciones especiales disponibles");
                                        //== == == =
                                    }
                                    if (numeroPersonas >= 0) {
                                        vistaPrincipal nvisPrincipal=new vistaPrincipal(arbol, reservas);
                                        nvisPrincipal.setVisible(true);
                                        this.dispose();
                                    }

                                }
                            } else {
                                JOptionPane.showMessageDialog(null, "No se ha podido realizar la reserva");
                            }
                        } else {
                            JOptionPane.showMessageDialog(null, "Teléfono no válido, intente nuevamente");

                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Edad no válida, intente nuevamente");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Número de documento no válido, intente nuevamente");
            }

        }
    }//GEN-LAST:event_BtnSiguienteActionPerformed

    private void HabComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HabComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HabComboBoxActionPerformed

    private void BtnVolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolActionPerformed
        vistaPrincipal pagPrin = new vistaPrincipal(arbol, reservas);
        pagPrin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnVolActionPerformed

    private void BtnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInfoActionPerformed
        VistaHabiPer1 pagHabiPer1=new VistaHabiPer1(arbol, reservas);
        pagHabiPer1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnInfoActionPerformed
    public static boolean CantCarac(String input) {
        // Verifica que la longitud esté entre 8 y 10 caracteres y que no contenga espacios
        return input.length() >= 8 && input.length() <= 10 && !input.contains(" ");
    }

    public static boolean CantCaracTel(String input) {
        return input.length() == 10 && !input.contains(" ");
    }

    public static boolean esNumero(String input) {
        // Verifica que el string contenga solo números
        return input.matches("\\d{10}");
    }

    public static boolean esLetra(String input) {
        // Verifica que el string contenga solo números
        return input.matches("\\d{3}");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaReserva.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaReserva.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaReserva.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaReserva.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaReserva(arbol, reservas).setVisible(true);

            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnInfo;
    private javax.swing.JButton BtnSiguiente;
    private javax.swing.JButton BtnVol;
    private javax.swing.JComboBox<String> EstadiaCbox;
    private javax.swing.JComboBox<String> FechaCbox;
    private javax.swing.JComboBox<String> HabComboBox;
    private javax.swing.JLabel Icono;
    private javax.swing.JLabel LbDatos;
    private javax.swing.JLabel LbDatos1;
    private javax.swing.JLabel LbDatos2;
    private javax.swing.JLabel LbDatos3;
    private javax.swing.JLabel LbDatos4;
    private javax.swing.JLabel LbDatos5;
    private javax.swing.JLabel LbDatos6;
    private javax.swing.JLabel LbDatos7;
    private javax.swing.JLabel LbDatos8;
    private javax.swing.JComboBox<String> NumPerCbox;
    private javax.swing.JTextField TxtEdad;
    private javax.swing.JTextField TxtNom;
    private javax.swing.JTextField TxtNumDoc;
    private javax.swing.JTextField TxtTele;
    private javax.swing.JLabel lbTitulo;
    // End of variables declaration//GEN-END:variables
}
