package gestionhotel;

import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class VistaReserva extends javax.swing.JFrame {
    vistaPrincipal nvista=new vistaPrincipal();
    ArbolHabitaciones arbol=new ArbolHabitaciones();
    Reserva nuevaReserva = new Reserva();
    
        int tipoHabitacion=0; //////////////////////////////////////////////////////////////
        String nombre = "";
        int nDocu = 0;
        int edad = 0;
//      int fechaReserva = 0;
        String telefono = "";
        int tiempoEstadia = 0;
        int numeroPersonas = 0;
        int diaInicial=0;
    /**
     * Creates new form VistaReserva
     */
    public VistaReserva() {
        initComponents();
        arbol=nvista.obtenerArbol();
        // Crear 4 objetos tipo habitación con esEspecial = false
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitulo = new javax.swing.JLabel();
        Icono = new javax.swing.JLabel();
        LbDatos = new javax.swing.JLabel();
        LbDatos1 = new javax.swing.JLabel();
        LbDatos2 = new javax.swing.JLabel();
        LbDatos3 = new javax.swing.JLabel();
        LbDatos4 = new javax.swing.JLabel();
        LbDatos5 = new javax.swing.JLabel();
        LbDatos6 = new javax.swing.JLabel();
        LbDatos7 = new javax.swing.JLabel();
        TxtNom = new javax.swing.JTextField();
        TxtNumDoc = new javax.swing.JTextField();
        TxtTele = new javax.swing.JTextField();
        FechaCbox = new javax.swing.JComboBox<>();
        TxtEdad = new javax.swing.JTextField();
        EstadiaCbox = new javax.swing.JComboBox<>();
        NumPerCbox = new javax.swing.JComboBox<>();
        BtnSiguiente = new javax.swing.JButton();
        LbDatos8 = new javax.swing.JLabel();
        HabComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(674, 700));
        setResizable(false);

        lbTitulo.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        lbTitulo.setText("Sistema De Reservas");

        Icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gestionhotel/imagenes/WhatsApp Image 2024-05-14 at 9.59.07 AM (2).jpeg"))); // NOI18N

        LbDatos.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        LbDatos.setText("Ingrese sus datos:");

        LbDatos1.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        LbDatos1.setText("N° de documento:");

        LbDatos2.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        LbDatos2.setText("Edad");

        LbDatos3.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        LbDatos3.setText("Nombre Completo:");

        LbDatos4.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        LbDatos4.setText("Fecha deseada para la reserva:");

        LbDatos5.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        LbDatos5.setText("Telefono:");

        LbDatos6.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        LbDatos6.setText("Tiempo de estadía:");

        LbDatos7.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        LbDatos7.setText("Número de personas:");

        TxtNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNomActionPerformed(evt);
            }
        });

        TxtNumDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNumDocActionPerformed(evt);
            }
        });

        TxtTele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTeleActionPerformed(evt);
            }
        });

        FechaCbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "22/05/24", "23/05/24", "24/05/24", "25/05/24", "26/05/24", "27/05/24", "28/05/24", "29/05/24", "30/05/24", "31/05/24", "01/06/24", "02/06/24", "03/06/24", "04/06/24", "05/06/24" }));

        TxtEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtEdadActionPerformed(evt);
            }
        });

        EstadiaCbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Noche", "2 Noches", "3 Noches", "4 Noches", "5 Noches", "6 Noches", "7 Noches", "8 Noches", "9 Noches", "10 Noches" }));

        NumPerCbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));

        BtnSiguiente.setBackground(new java.awt.Color(153, 204, 255));
        BtnSiguiente.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        BtnSiguiente.setText("Siguiente");
        BtnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSiguienteActionPerformed(evt);
            }
        });

        LbDatos8.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        LbDatos8.setText("Tipo de habitacion:");

        HabComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Habitación Estandar Waos", "Habitación SuperWaos" }));
        HabComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HabComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(lbTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Icono))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LbDatos1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtNumDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LbDatos)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LbDatos2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LbDatos6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EstadiaCbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LbDatos7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NumPerCbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LbDatos3)
                                .addGap(18, 18, 18)
                                .addComponent(TxtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(LbDatos5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TxtTele))
                                    .addComponent(LbDatos4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FechaCbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LbDatos8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(HabComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 110, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BtnSiguiente)
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Icono))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lbTitulo)))
                .addGap(2, 2, 2)
                .addComponent(LbDatos)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbDatos3)
                    .addComponent(TxtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbDatos1)
                    .addComponent(TxtNumDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbDatos2)
                    .addComponent(TxtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbDatos4)
                    .addComponent(FechaCbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbDatos5)
                    .addComponent(TxtTele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EstadiaCbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LbDatos6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbDatos7)
                    .addComponent(NumPerCbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSiguiente)
                    .addComponent(LbDatos8)
                    .addComponent(HabComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNomActionPerformed
        
    }//GEN-LAST:event_TxtNomActionPerformed

    private void TxtNumDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNumDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNumDocActionPerformed

    private void TxtTeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTeleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTeleActionPerformed

    private void TxtEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtEdadActionPerformed

    private void BtnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSiguienteActionPerformed
        nombre = TxtNom.getText();
        nDocu = Integer.parseInt(TxtNumDoc.getText());
        edad = Integer.parseInt(TxtEdad.getText());
        telefono =TxtTele.getText();
        tiempoEstadia = (EstadiaCbox.getSelectedIndex())+1;
        numeroPersonas = (NumPerCbox.getSelectedIndex())+1;
        diaInicial=(FechaCbox.getSelectedIndex())+1;
        tipoHabitacion=HabComboBox.getSelectedIndex();
        if (nuevaReserva.ReservarHabitacion(diaInicial, tiempoEstadia)) {
            if(tipoHabitacion==0){
                JOptionPane.showMessageDialog(null, "existe");
                JOptionPane.showMessageDialog(null, " indice =   "+arbol.dispHabitacionesNormales());
                if(arbol.dispHabitacionesNormales()>=1){
                    JOptionPane.showMessageDialog(null, "existe---------");
                    nuevaReserva = new Reserva(nombre, nDocu, edad, telefono, tiempoEstadia, numeroPersonas,arbol.dispHabitacionesEspeciales());
                    int index=arbol.dispHabitacionesEspeciales();
                    arbol.habitacionesNormalesEnc(index);
                    arbol.printInOrder();
                }
            }
////            if(tipoHabitacion==0){
////                nueHabitacion3=new Habitacion(2);
////                nuevaReserva = new Reserva(nombre, nDocu, edad, telefono, tiempoEstadia, numeroPersonas,nueHabitacion3.getNumHabitacion());
////            }else if(tipoHabitacion==1){
////                nueHabitacion1=new Habitacion(0);
////                nuevaReserva = new Reserva(nombre, nDocu, edad, telefono, tiempoEstadia, numeroPersonas,nueHabitacion1.getNumHabitacion());
////            }
            
            JOptionPane.showMessageDialog(null, nuevaReserva);
        } else {
            JOptionPane.showMessageDialog(null, "No se ha podido realizar la reserva");
        }        
       if(numeroPersonas==1){
           VistaHabiPer1 habiPer1 = new VistaHabiPer1();
           habiPer1.setVisible(true);
           this.dispose();
        }else{
           VistaHabi2Per habi2Per = new VistaHabi2Per();
           habi2Per.setVisible(true);
           this.dispose();
        }
    }//GEN-LAST:event_BtnSiguienteActionPerformed

    private void HabComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HabComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HabComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaReserva().setVisible(true);
                
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSiguiente;
    private javax.swing.JComboBox<String> EstadiaCbox;
    private javax.swing.JComboBox<String> FechaCbox;
    private javax.swing.JComboBox<String> HabComboBox;
    private javax.swing.JLabel Icono;
    private javax.swing.JLabel LbDatos;
    private javax.swing.JLabel LbDatos1;
    private javax.swing.JLabel LbDatos2;
    private javax.swing.JLabel LbDatos3;
    private javax.swing.JLabel LbDatos4;
    private javax.swing.JLabel LbDatos5;
    private javax.swing.JLabel LbDatos6;
    private javax.swing.JLabel LbDatos7;
    private javax.swing.JLabel LbDatos8;
    private javax.swing.JComboBox<String> NumPerCbox;
    private javax.swing.JTextField TxtEdad;
    private javax.swing.JTextField TxtNom;
    private javax.swing.JTextField TxtNumDoc;
    private javax.swing.JTextField TxtTele;
    private javax.swing.JLabel lbTitulo;
    // End of variables declaration//GEN-END:variables
}
